version: '3.3'
services:
  service:
    image: poc/prom-metrics-service
    ports:
      - "7000:7000"
    networks:
      - poc
    depends_on:
      - prometheus
      - grafana
    labels:
      org.label-schema.group: "service"
  grafana:
    image: grafana/grafana:5.4.3
    ports:
      - "3000:3000"
    networks:
      - poc
    volumes:
      - /var/lib/grafana
      - '../configs/grafana/provisioning:/etc/grafana/provisioning'
      - '../configs/grafana/dashboards:/var/lib/grafana/dashboards'
    environment:
      - GF_SECURITY_ADMIN_USER=poc
      - GF_SECURITY_ADMIN_PASSWORD=prometheus
      - GF_USERS_ALLOW_SIGN_UP=false
    depends_on:
      - prometheus
    labels:
      org.label-schema.group: "monitoring"
  prometheus:
    image: prom/prometheus:v2.7.1
    ports:
      - "9090:9090"
    expose:
      - 9090
    networks:
      - poc
    volumes:
      - '../configs/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml'
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    labels:
      org.label-schema.group: "monitoring"

networks:
  poc:
    driver: bridge
