version: '3.3'
services:
  service:
    image: poc/prom-metrics-service
    ports:
      - "7000:7000"
    networks:
      - poc
    depends_on:
      - prometheus
      - grafana
    labels:
      org.label-schema.group: "service"
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    networks:
      - poc
    volumes:
      - /var/lib/grafana
    depends_on:
      - prometheus
    labels:
      org.label-schema.group: "monitoring"
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    expose:
      - 9090
    networks:
      - poc
    volumes:
      - '../configs/prometheus.yml:/etc/prometheus/prometheus.yml'
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    labels:
      org.label-schema.group: "monitoring"

networks:
  poc:
    driver: bridge
