global:
  scrape_interval:     5s
  evaluation_interval: 5s

  external_labels:
      monitor: 'prom-poc'

rule_files:
  # - "alert.rules"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'poc-service'
    scrape_interval: 1s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['service:7000']
