# config file version
apiVersion: 1

datasources:
 - name: Prometheus
   type: prometheus
   access: proxy
   editable: false
   isDefault: true
   orgId: 1
   url: http://prometheus:9090
   basicAuth: false
   version: 1
